### PR TITLE
[Discussion] Removes unwelcoming language

### PR DESCRIPTION
**Pull request by MrsTonedOne**
This is a thread to allow for continued discussion.

Comments made here will be edited into my comment in the real pr at https://github.com/todogroup/opencodeofconduct/pull/56 when ever I remember to.

And maybe some day @bkeepers will learn that you just can't stop the signal, you can never stop the signal.

### CODE REVIEW

**Comment by thor** [comment]
> The intent of the open code of conduct is to help establish communities that are safe and welcoming for _everyone_. At some point, the moderators of a community are going to have to make tradeoffs. The language in question is attempting to guide how those tradeoffs are prioritized, not to encourage hostility.

I am having a hard time seeing how creating a biased discrimination filter creates a safe and welcoming community for _everyone_ -- would it not be ideal to establish a absolutely fair and even set of guidelines that apply to _everyone_ if one wants _everyone_ to be equally safe and welcome? :unlock: 

> [..] if we can clarify the language to communicate that.

Hopefully there is a way to clarify that without imposing perceived biases on communities as a default?

**Comment by MrsTonedOne** [comment]
@bkeepers:

> The intent of the open code of conduct is to help establish communities that are safe and welcoming for everyone. 

Yep! Everyone.

> At some point, the moderators of a community are going to have to make tradeoffs. 

[citation needed] You disallow discrimination, and you disallow discriminatory language, no trade off necessary.

> The language in question is attempting to guide how those tradeoffs are prioritized, not to encourage hostility.

Again, not needed. There are no tradeoffs involved, this isn't a zero sum game.

> I will seek feedback from people that have been invested in crafting and adopting this document to see if we can clarify the language to communicate that.

And I'm going to insist that there is no way such "priority" can co-exist with a safe and welcoming environment.

> I am also going to lock this thread while I do that.

I see no need for this, and it's easily thwarted. This seems like you trying to ensure you got the final word in.

> Know that your feedback is being taken seriously.

Heh. Is that why you locked the pr in an attempt to ensure your privileged position in the discussion. Get the final word in, and call it good. "but know that your feedback is being taken seriously" The tried and true words of people who want to silence criticisms they aren't comfortable with.

**Comment by ELLIOTTCABLE** [comment]
Wow, this is fucking ridiculous.

The creators and maintainers of _this project_ have made themselves clear to you, @MrStonedOne (your name, too … just, wow.) They offered to take your concerns seriously (more, by the way, than they are _in any way_ obligated to do), but it's entirely their right (and a damned good decision) to shut down the potentially-unproductive discussion while they decide whether they're compfortable making those changes.

This is an open-source document; you're welcome to fork it, if the maintainers end up disagreeing with you; and tell people of your concerns with the original / point out your forked efforts at improvement.

Pulling _this_ “ooo my freedom of speech is being quashed!!1!” stuff is a really good way to get those concerns ignored completely. Well done, sir, well done.

**Comment by MrsTonedOne** [comment]
> Pulling this “ooo my freedom of speech is being quashed!!1!”

Actually, I said they tried to stop discussion, nothing about free speech.

> your name, too … just, wow.

Some people drink alcohol, they might even make a username on that, some people smoke weed (and they too might make a username on that) I see no issue, it's all 21+ legal, so whats the issue? I'm over 21(25), I am legally allowed to smoke marijuana, and I refuse to make it a secret part of me because somebody wants to use it as an excuse to look down at me.

**Comment by KelseyDH** [comment]
:+1:

**Comment by apullin** [comment]
:+1:

In the other threads, I have seen it stated that it is a non-starter to discuss the material nature of the items being removed. There should be a motion for estoppel with whichever pertinent committed or governing bodies for the project, with respect to the inclusion of any disputed elements being included. Hiding one dispute behind another is poor design and leadership.

If GitHub intends to adopt this policy, then I am de facto directly involved with it, as I have made agreements, both contractual and financial, with GitHub. The is true for organization that stated intent to adopt this document, and for any persons who have any transactions or contracts with them.

@ELLIOTTCABLE, you are personalizing this is a fruitless way. I am certain that I have done myself this with difficult issues in the past. I only offer this to try and level the hotness of the personal politics that pervade this issue.

**Comment by tkerber** [comment]
:+1:

I cannot see myself contributing to any project using the open code of conduct unless this is removed.

I do not think that todogroup should inject their own ideology into a document which is supposed to protect **people**.

**Comment by hgmich** [comment]
:+1:

The spirit of open source is to allow equal access to all without qualification or discrimination, and a company whose business in invested in it should follow those principles. A community seeking to be accessible to everyone should not promote a one way street on the policing of negative behaviour.

**Comment by Karunamon** [comment]
:+1:

This kind of nonsense seriously impacts my desire to use Github for any projects, personal or otherwise, in the future. It's clear the site leadership values ideology more than Getting Shit Done©

**Comment by hemsleyk** [comment]
Codes of conduct are not a means for legitimizing people being abusive online. They're meant to stop that. And the old Open Code did. Please do not grant special protections to abusive users like https://github.com/freebsdgirl

**Comment by xjeffw** [comment]
:+1:

This kind of language only serves to antagonize every person who does not share the ideology of the authors, and it would be foolish for any project to alienate a great number of people by including it.

**Comment by yackermann** [comment]
I would like to point out that language is way to tricky thing to allow or ban words or so. Take for example repository thefuck https://github.com/nvbn/thefuck. Just because it uses word fuck, it does not mean it is bad. Besides, I would like to point out that we are all fucking using abusive words ALL FUCKING TIME. Irony. Thats take general words usage.  

Now about cultural. Word "Nazi" in Israel and many other WW2 countries have VERY DIFFERENT interpretation in countries that were not part of the war directly. But it does not stop us from using words like GrammarNazi etc. Another example Russian word Blyad(Блядь). In church it means "The person who lost its way" and in normal day life it means "whore". There very different connotation.

Now about general shit. I am fully agree with @Karunamon that we are GIVING TOO MUCH FUCKS about politically correctness instead of GETTING SHIT DONE. And perhaps Linus Torvalds will not agree with such a rule either because well...https://www.youtube.com/watch?v=_36yNWw_07g.

Now about words and change of a meaning over the time. Most of the old people remember word "gay" as meaning "happy", but today its general usage means "homosexual", thats a good example. Russian word from my childhood Drachuny(Драчуны) mean "Kids who like fighting with everyone" now means "Wankers"(A person, especially a man, who masturbates.).

I don't agree with any form of bullying. But abusive language is very arguable subject, and banning of it will harm society more then it would help. People should learn defend the ones who get bullied. People should learn that there other people who will not have the same view point. And they should learn defend them selfs as well. Plus there is not help to anyone if someone will be shut based on its word usage. Its like "Oh! eval() in JS is bad. Lets just ban it." but even eval() has its own use, and so swear word FUCKING ARE!

**Comment by hemsleyk** [comment]
@herrniemand Abusive does not mean offensive, and vise versa. Code of Conduct needs to focus on abusive language, and somewhat less so on offensive language, without special protections allowing someone to be as abusive and toxic as they want so long as they aren't a white male.

**Comment by yackermann** [comment]
@arthurkay that come under general abuse. Because "Sir, I think you are lacking of some encephalon mater in your cephalic bone structure." is quiet polite way to say "You are fucking stupid."
As an example. I am trying to abuse anyone. LOL

**Comment by snickerbockers** [comment]
I'd like to see somebody who opposes this pull request try to provide definitions of what "reverse racism" and "reverse sexism" are supposed to mean without contradicting the code of conduct's first definition of harassment.

**Comment by yackermann** [comment]
@jayelliott same.

**Comment by just3ws** [comment]
As someone who once had a gun pointed at me with death threats for being white, among other experiences. I'd like to know whether those incidents would count as reverse racism thus I would have no right for recourse or complaint under the current CoC.

**Comment by just3ws** [comment]
What if a person who is from a protected group witnesses and reports an incident of "reverse racism" because it is causing an incident of hostility thereby making them uncomfortable? Would the privileged target of the reverse racism being the one asked to leave because their safety is not as important as the comfort of a protected group member? How would that be sorted out?

**Comment by LimeBlast** [comment]
:+1:

**Comment by yackermann** [comment]
@jayelliott @just3ws 

Reverse racism is a condition in which discrimination, sometimes officially sanctioned, against a dominant (or formerly dominant) racial or other group representative of the majority in a particular society takes place, for a variety of reasons, often as an attempt at redressing past wrongs. It has been described as "preferential treatment, discriminating in favor of members of under-represented groups, which have been treated unjustly in the past, against innocent people".

Example: Maoris in NZ, Afroamericans in US

**Comment by KelseyDH** [comment]
@herrniemand One compromise could be rephrase the language to be more inclusive, better defined, and less divisive.  For example, by removing the current language targeted by this PR and replacing it with a sentence like this (borrowed a bit from the Canadian Charter):

```
We will not act on complaints regarding:

- Good faith and non-malicious conduct whose object is to ameliorate the conditions of disadvantaged individuals or groups including those that are disadvantaged because of race, national or ethnic origin, colour, religion, sex, age or mental or physical disability.
```

This compromise could preserve the good intentions of what the authors of the original sentence were going for, without necessarily "taking sides" or incorporating language that only narrowly focuses on the priorities of specific rights movements.

**Comment by ghost** [comment]
@KelseyDH is on point with this.

:+1:

**Comment by yackermann** [comment]
@KelseyDH @ConcernedUsurper :+1:

**Comment by yackermann** [comment]
@KelseyDH could you please explain me this bit. I am just a bit confused

##### Physical contact and simulated physical contact (eg, textual descriptions like “hug” or “backrub”) without consent or after a request to stop

**Comment by LimeBlast** [comment]
@KelseyDH yes, that is so much better. I admit, I had to look up the word "ameliorate", but having done that, I can read and understand what this line means, unlike the original line - reverse what now?

**Comment by yackermann** [comment]
@KelseyDH so you can not write someone "hugging you" as if it is offending someone?

**Comment by KelseyDH** [comment]
@herrniemand My comment was only specifically in reference to the content of this pull request, it was not a general statement in favour or against other wording in this Code of Conduct as its currently written.

But to respond to your question about how we should adequately define harassment, I believe adding more clarifications to the harassment section could help ([e.g. here's one example of how that can be done.](http://www.chrc-ccdp.ca/eng/content/what-harassment)).  The opening sentence could be rewritten to read:

```
Generally, harassment is a behaviour that persists over time. Serious one-time incidents can also sometimes be considered harassment.  Harassment includes, but is not limited to:
```

---

Finally, I also recommend adding specific prohibitions against _bad faith_ or _vexatious_ complaints. [Here's one detailed breakdown by a Canadian human rights commission.](http://www.tbs-sct.gc.ca/psm-fpfm/healthy-sain/prh/gahrp-gaprh-eng.asp#toc3-2-2-1)   For a Code of Conduct document like this which strives to be readable, similar language could be added to the bottom of the Harassment section that reads:

```
For the complainant, we will not act on a complaint if:

- There is evidence of bad faith on the part of the complainant indicating an intention to mislead.
- It is made intentionally for the purpose of vexing and annoying or embarrassing a person.
```

**Comment by dls** [comment]
I think this basically *has* to be the text for a truly general code of conduct. If you're accepting code commits from all over the world, there's not real basis for deciding what is and isn't a reverse ism.

For an example, consider a white developer living in Japan. The white developer is a minority locally and is encountering systemic bias every day (feeling othered, feeling exotic, feeling self-concious, feeling sensitive on the topic of their race, feeling judged on the basis of their race, etc). It's likely this person will find reverse-racism quite painful. Codifying that their suffering will not be acted upon isn't cool.

(Not to put too fine a point on it, but if that sounds absurd to you I encourage you to read about Japan's race problem. Preferably from Japanese sites using Google Translate if need be. 右翼団体 is a good starting point. I imagine that India, China, Korea, Africa, etc have similar problems, though I know less about the culture of those countries.)

Which is to say that while I think the spirit of the no reverse-ism clause is a good one -- giving increased acceptance and leniency to those who have a harder time finding communities to participate in -- as worded, the code of conduct seems to miss that it's the context of the *person being oppressed* that matters, not the context of the *project maintainers*... as a project grows the number of no no-big-deal-isms/reverse-isms goes to zero.

**Comment by jayyoung** [comment]
Please just erase the whole thing and change it to say "Be excellent to each other".

**Comment by LimeBlast** [comment]
Jesus says: don't be a dick

**Comment by just3ws** [comment]
@herrniemand I once tweeted something like "RTs are like hugs" on a project, and got a genuine response that the tweet was unwarranted and something about "unreciprocated romantic interest". So, yeah. Some people don't like the word "hug".

**Comment by yackermann** [comment]
@just3ws Maybe it is because I am Russian, but:
steamworkshop_webupload_previewfile_393207598_preview
I think I stoped understanding this planet.

**Comment by ghost** [comment]
This is the development of a Code-of-Conduct for individuals contributing to the development of software, this isn't the development of a national-level social policy affecting all aspects civic life.

How appropriate is preferential treatment, discrimination in favor of members of under-represented groups, in software development teams? For what end? This is an exercise in levying the cock-eyed social preferences of some folks upon GitHub users because they can. If GitHub developers were devout Christians we should all have to pray to Jesus before coding?

Please take this pull request as a start in fixing your CoC.

**Comment by MrsTonedOne** [comment]
This keeps clouding my current pull requests page

**Pull request closed without merging**
